---
# This playbook contains all of the common things every machine in the site gets.  Basic packages, users, etc etc.

- include: packages.yml
- include: users.yml
- include: apache2-mods.yml
- include: ufw.yml
- include: znc.yml
- include: bzflag.yml
- include: minetest.yml
- include: minecraft.yml
- include: dovecot.yml
- include: postfix.yml
- include: iris.yml
- include: gopher.yml
- include: pb.yml
- include: botany.yml
- include: vnc.yml
