---
- user:
    name: amcclure
    groups: tilde
    state: present
    skeleton: /etc/skel
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/amcclure
- authorized_key:
    user: amcclure
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFheJihLfXJ4jg2bRKKAErB76fw8izDxpg4dFibaQage amcclure@Antons-MacBook-Pro.local"
- authorized_key:
    user: amcclure
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIqNf2mD3RiJY5ZQtRhgg5xRD4a6whdBdh+xiCnfZ7fw amcclure@solaris"
- authorized_key:
    user: amcclure
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAb/LEff3etQLEEF6L61KyTkxXfsI6tJwV161oSoPkyb amcclure@gowinnt"
- authorized_key:
    user: amcclure
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIMF+N1NxdN2SBb7Yyk+d4ThVoO87bRSYhEqgR2K9gA4 amcclure@lake"
- authorized_key:
    user: amcclure
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGCA/TGxVNNVHevXq96yrMT3suUrPO+v93NqLC2wjEv0 anton@antonmcclure.com"
