---
- name: Setting up cyphyx
  user:
    name: cyphyx
    groups: tilde
    state: present
    skeleton: /etc/skel
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/cyphyx

- authorized_key:
    user: cyphyx
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKqC9q9QPqGqOuOb9DimlrA/RxzzLPfnMwZyngQBRPROsCrDlgAD42y8UWvlpTPxEZOI+PVSOkts3IFyeH2b3r6PZd8rSyl/5PiEBX1fcyiza9XJDw6nsicKIG8RzfQ6wlxL3692qNVgtKAUT+W+Mv2u62AV/CUh4UERN/XuFpUlGGkGFPWBsNwv7Z70oC459bZJ7ZZSmfJkBLnyW/I/poEbEIkpevx/qjFu+1z+UuAAyY1OO/RodVhVIs5x7MSONKTn/3gwXsdH7E8ZoRfN9ur50mySmWMKMbssmnG1xoOVRKlAaK3DttG7vLxBBtrdoSzQVS01Bd+qi9P7vhzo2cSCZovcfA+E4zDdwb0ZCy9kLpzpbOIqu+4QyALFzEvBkbyQsMdBqutzM5muk/p5QCZU7Tfy6/R4kGhT3GrQ+3gEZX/OKtaFbj8a2plccBcizdmO3ArlViw78Rw2YgGuIslXOu0/BLHR/kLcP8QkzbBqoobVU2dqxriZUcZ4VFWS36YrN0NB3mOd6rpEp28a7vZRlmj0I3hZnMdl6knHZfre0ZrbyCL2t05aABh348Ny7cQOmsjlAkNqyeB5JIevfz5Bq/kRrGQH4xcEtvhjo6j/ifdu2AQfLG30MtrxZb8FkEQEOQxwkruipySm18cG9H4ssNSwPFH2SmOPizOdpLMQ=="
