---
- name: Setting up faabb
  user:
    name: faabb
    groups: tilde
    state: present
    skeleton: /etc/skel
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/faabb
- authorized_key:
    user: faabb
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBf2nLLUC99OmVFgU3veTZORYs1oa4FJ2Mmhoa3FoM9ij/rGzGBjEpEwB75o5v2T1N9hHy56VS5yZ1ITpIIx4wNN1VUfYTho1yIaiIZTi3+K7yTte7npj5uB/Fs411H3uXGnh9b1e0g0flfxTEZAjJJQy/ZDh1lCIqcseMf2m4Qyim2A8O7/J39CcpSQtMWbxHRc1P4aHM3GfCACCjVvGjSjcKutsP8QJGy0AR8/sXAqvaetIfeCBCBTUCZc3kMuQTG3nYzvpzE3bE6jhqrWGELVp8aznJdiU//Lvo5fURRCwEhNfDyLG6ZOtgK30heWi17tBQKqhCZ0ljA0y9hvAd too"
