---
- user:
    name: thefunkyspaw
    groups: tilde
    state: present
    skeleton: /etc/skel
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/thefunkyspaw
- authorized_key:
    user: thefunkyspaw
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA1jqH/VkGFXHZZU7jdqjfP5+duqBlzSTb3Ve5A2TujU thefunkyspaw@global"
