---
- name: Setting up ubergeek 
  user:
    name: ubergeek
    groups: tilde,sudo
    state: present
    skeleton: /etc/skel
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/ubergeek

- authorized_key:
    user: ubergeek
    state: present
    key: "ssh-dss AAAAB3NzaC1kc3MAAACBAIBSqyxUGJOtsY+ri6SWRl7SyLO0dTK0uiTVWhzt/nzNGZsmvfSteasQGOrMpEgrnWDCm7XahH/AUg5IgSDmU7gKWITZVUqZGk8zZbqmx/qQuNqnte6J3vQvQK7M6qShVpnrLFdoEyrXjljAqGVVV4nyB0n+GBBJ1WlJN/eyJt3lAAAAFQDKpycDN2+ga6d53bYyReVVoOFcgwAAAIB4a4GPZsmJJc9bSnHU5j2pt6ThMS3yud//K46TGNF9vX5EXVrWk9XZc/iPwiXOnHfTu2uoVJiJkhJEM3SQY0YO0DoEqoCfwdZ+SisQeLDat/mvNduXO2PdVoKodXftwr1dq1HMD+0Wi+b17G1E/Gfx76ECfA3mBFvdsu8Wgo+I4wAAAIAy3QFkmetRKi/XjSMiiyJa1jxKiNyTO97eU2kLFyQE7LMQ6agDACPk3yfMdUgH7tvjfOBH5Tsp3wS+nvx1I7M5w08z88F9NBrp8Z2Ni2nACLtbY5q5oFr0a7ZnD+6LbWksK8NcTAquBnxf4FzXJ+knDfAg8Oya0sqR95VV5xoVTw== ubergeek@ubergeeks-MacBook-Pro.local"
- authorized_key:
    user: ubergeek
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdgDD3UMyI9NdtVGuuDS1Rqfw6YoJsctAhWgGP+0w6MX5Od0B3km6C/BaMe/ZY7vA861wjoeHFdZ69nOYsdDqysCLxZCAfGBjzYM2mS4UiuV3tnZA7C/Zd+dGUfuA64iQ1SJ3FcehGezgI9zJU2JSWfhzHO2gx7fdZ9lhCEDU3qkiXy6HFzd+B0+tlEXBSkUk4g47ZLuaKxPrqeug5xGLwjlMjTSYSyhODdjvYQNkaD4ynyggdq21T0CWA5abH4nol+NPy5HChYH7wkA0qQ23GeUrUfdWmzZxua6SBVEGC0cFiLLt0ZPCf2foob7Nse6W3ISy85uBKO4QNO5Nwl+zz ubergeek@yourtilde.com"
- authorized_key:
    user: ubergeek
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWBuCQwCmSfgH7FSI1smAex7uDY1zUNSYets5OmLrHNgMi3daCv6TngwQCjdb3LDkIRsCAbz1z3vGaeycrNLQMLCcxTRXRQRWftJ8sVKXgJicxb13mzYM+2QwtYNIEc7lCECV7++EuiGEYqk/oBp+j3j29lhqg76SDLb4C1yvGCZOT0R6IBIXf8DQ7qqQmYiEIdCdfRkwEB4euNuyW0w9Mr/jg6xpBB5H0wDJo6zOTvj04MfQ4Zk58ZMoFu9mPHaWzrm7Q1RaeKmghGRzNJUp6o5lle0Q2pgvzbuB07/utxloBHqwyQn8wUjdczUvejOBxwi4aCBfD5ba5VZGhQSod"
- authorized_key:
    user: ubergeek
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHC99QzEk4P0XD28+5rHBoaeKVURy170Df3qT4IWSwm8bpj1GySCEYXdcFPB1z/U9OZi5k9UQA2CUwl6RJxkHukIvrsx78C36dWoOz4X3Hw1G4bUthRspdyHZBnlasDe/rJPHZmfJNTvrGs8cZu9PqaN77+ceMomfG7ESemuVZeimhiq/FXfiqfAlH6nNJaZ/b53MQtMOUrcFt2qnEzQ+L+5OUc14pRZj9BpKFtLFX6zkAvNb2l+iQ+enzUPfyikQun8E+C3wsOZlkmMBjXCO27iJkWL0EM1yC3q2ZEPO7cyf2Yhf7y4jt90HeY4VLbC9ObeNeyvOgrpxng9elI1lZ"
- authorized_key:
    user: ubergeek
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDrZ1A4dkJlP3gXaZto6ct6xTs5o1nhCFIflP+OXBbTlOQCgeCGoiPelpRhe+1x3TD99u50/k4JF/NCA4xRaeYnWFDkWx1P0NHv4nAdwAACIH8SrUiSbeZrogPApVpfuMkVvU5y7DthMgTAJbF13EaKsqVTmD9eVSlSStYgWU+Y+9Ip22BdANcJuCtpd+99DSPSRA14bFndMN3or980O9DA5oSk36uwrNSHhAObRHRQdcFVYwEHtrffI4ZYuuFo6qQzLHI1yFcIlJ8Xyaru+MqILfT2eSetBZwnHwrZSlIKwCw2tYclDmnH3W2nytQ7hAHJIsrB67++Usd6OlF2N/5tMu6c9YGPXu3AAgNos1R6kvlL22e+OVXaLOBqXSBNZjBjnrvuO+0PvRNEBoSeqALmjkgQkTPbzXgeAYFNDJtgydAuJwcGKq6QD0f94KibpoKP7NXbZPtJDax/MStoQzDImUz84b1H6NgPX9ddDcH8emhf+v6SB1OHZMPgO9dGGRjEIanj2v2bgGDO3zzv+emOaWrq/KVFFMFL+TKuneujCwKrAsCwrjomPNGtRd92FU65KTpwzN91Y3g2fkMTg2iYqXhHnVHgaf8nBwRoyK0TCDrUdcxHJHGafO3EoY+HiHhOyMV/CDvppL8e4nIGR5CZazDfKuEdEeiSsnCdzD0Anw== u0_a313@localhost"
- authorized_key:
    user: ubergeek
    state: present
    key: "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAA0NYVVAp4bcJlPCXU9HRHAwJHoyfI4IN0H6Tx/fdf56dzB6hR7SCKFLdmhaFkCZnlGWd4rLN1Phrem26ncsiOsBwEjzPFdlyOVCXfvheK17RsNT/D8zHXI6P06Soz0WzNCYD5NUVwtQJvs6ptA6fMUCOlmZapxyUW4pjMLkCbRKhuxQw=="
- authorized_key:
    user: ubergeek
    state: present
    key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBL0VsUZQ9Rv+ATjE8q/gaaP/rM7tcae8Y/YDwKldnwEUvDjopv7TPiiQvoQXCC0CTqoscmyU3JSpn9jTJHYXQKs= dextop@localhost"
    