# Enable or disable apache2 mods
---
- name: userdir
  apache2_module:
    name: userdir
    state: present
- name: ssl
  apache2_module:
    name: ssl
    state: present
- name: php7.3
  apache2_module:
    name: php7.3
    state: present
- name: rewrite
  apache2_module:
    name: rewrite
    state: present
- name: proxy
  apache2_module:
    name: proxy
    state: present
- name: proxy_http 
  apache2_module:
    name: proxy_http
    state: present
